### ISSUE TITLE
Does not read API key from environment

### ISSUE THREAD

**Issue by twingly-mob** [xSAVIKx/twingly-search-api-java#8]
The API key is not read from the environment, to reproduce: `export TWINGLY_SEARCH_KEY=<the-key>`, this generates:

> Api key was not found in TWINGLY_SEARCH_KEY environment variable, please set it.

Seems like the code is using `System.getProperty(string)`, but it could be `System.getenv(string)`.

Looks like it would be hard to make a test for this though as Java does not really seem to have a good way of setting environment variables. What's your opinion, is it common practice to use property files rather than reading from environment for Java devs?

If the property file is the way to go, we believe that the error message needs to be adjusted to something like:

> Api key missing, could not find TWINGLY_SEARCH_KEY property

and something added to the README concerning the setup of using properties

**Comment by xSAVIKx** [comment]
`System.getProperty` is java related property, that should be passed as -Dproperty_name=property_value to when java is starting.
`System.getenv` is getting properties from OS environment variables.
So, actually, you just need to decide from where it should be get ?
As for me, I think that Java properties are more suitable here, cause you dont need to set OS env properties.

**Comment by walro** [comment]
Ah, thanks for the explanation. TIL `-Dproperty_name=property_value`. But maybe the error message needs to be changed anyway?

**Comment by xSAVIKx** [comment]
OK, will change it.

**Comment by xSAVIKx** [comment]
Or, maybe, it should really be OS env variable...
@twingly-mob , @walro 
What do you prefer ?

**Comment by walro** [comment]
It doesn't matter to us I think, as long as you can pass the key commandline in some way it's fine. As we said above, creating a test for setting env seems to be hard as there's no `System.setenv(...)`

**Comment by twingly-mob** [comment]
Tried it, works fine!

**Comment by dentarg** [comment]
Sorry haven't followed this closely, what did we end up with?

IMHO we should support ENV, because that's what you use at platforms like Heroku. But perhaps via command line is enough, ENV will be available for commands in the Procfile

**Comment by walro** [comment]
@dentarg We ended up with using Java properties, good point concerning Heroku though. I think this is fine for now as setting environment via Java seems to be a hassle (which you need to be able to do in order to test the feature properly), there's no API supporting it and you'd have to resort to black magic reflection. That's my understanding at least.

We _could_ add "experimental" support from reading from env (i.e. not 100% covered by tests) if we think it's needed in the future. Again, my understanding is that it's more common to read settings from properties than from the system environment in the Java world, but I might be completely off here. :)

**Comment by dentarg** [comment]
Yeah, I agree with java properties, I think I have seen other projects use that and in the Procfile read values from ENV for the properties
